site_name: OpenClaw Docs
site_description: Local AI Agent Orchestration with MCP
docs_dir: docs
site_author: Jeonghun Lee
repo_url: https://github.com/JeonghunLee/local-ai-agent-mcp
repo_name: JeonghunLee/local-ai-agent-mcp

# index.md 가 없으면, (내부용 )
# 1. Home 모든 404 오류 
# 2. mkdocs build 후 링크가 다 깨짐  
nav:
  - Home: index.md
  - Architecture:
      - System Design: architecture/system-design.md
  - Agents:
      - Claude: agents/claude.md
      - Claude Setup: agents/claude_setup.md
      - Claude MCP: agents/claude_mcp.md
      - Codex: agents/codex.md
      - Ollama: agents/ollama.md
      - Ollama Setup: agents/ollama_setup.md
  - MCP:
      - MCP Server: mcp/mcp_server.md
  - Environments:
      - Windows WSL2 Setup: environments/window_wsl2_setup.md
  - Experiments:
      - OpenClaw Test: experiments/openclaw_test.md
  - Logs:
      - run_001: logs/run_001.md

plugins:
  - search
  - mermaid2
  - offline

# Material theme configuration
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  language: ko
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - toc.follow
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.tooltips
    - content.code.copy
    - toc.integrate         # 이 줄이 TOC(Table of Contents)를 왼쪽 내비(sidebar)로 통합해줌 

markdown_extensions:
  - admonition              # 
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji     
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JeonghunLee
      name: GitHub


copyright: >
  © 2026 Jeonghun Lee.
  All rights reserved.
