#
# Site information
#
site_name: AI Agent with MCP
site_description: AI Agent with MCP 
site_author: Jeonghun Lee

#
#  Repository information  (우측 GitHub Icon 클릭 시, 해당 링크로 이동)
#  (주의: release 시 표시됨)
repo_url: https://github.com/JeonghunLee/local-ai-agent-mcp
repo_name: JeonghunLee/local-ai-agent-mcp

# index.md 가 없으면, (내부용 )
# 1. Home 모든 404 오류 
# 2. mkdocs build 후 링크가 다 깨짐  
nav:
  - Home: index.md
  - Architecture:
      - System Design: architecture/system-design.md
      - Automation Design: architecture/automation-design.md
  - Agents:
      - Claude: agents/claude.md
      - Codex: agents/codex.md
      - Ollama: agents/ollama.md
  - MCP Gateway:
      - Overview: mcp/mcp_gateway.md
      - MCP Server-Github: mcp/mcp_server_github.md
      - MCP Server-Local: mcp/mcp_server_local.md
  - Envs:
      - OpenClaw WSL2 Setup: envs/openclaw_wsl2_setup.md
      - GitHub Templates: envs/github_templates.md
      - GitHub Self Hosted Runner: envs/github_self_hosted_runner.md

#
# Plugins configuration
# 
plugins:
  - search
  - mermaid2
  - offline

# Material theme configuration
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  language: en
  # My Site Logo and Favicon
  logo: imgs/logo.jpg     # my logo
  favicon: imgs/logo.jpg  # my favicon    
  
  # Material for MkDocs (Menu 3 개 섹션)
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


  features:
    - toc.follow     # TOC(Table of Contents)를 스크롤에 따라 따라다니게 해줌
#    - toc.integrate      # TOC(Table of Contents)를 왼쪽 내비(sidebar)로 통합해줌, PC,Mobile(원래부터됨)     
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.tooltips
    - content.code.copy


markdown_extensions:
  - admonition              # Note/Warning box https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.arithmatex     # Math support https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:   # Material: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji     
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences: # Material: https://squidfunk.github.io/mkdocs-material/reference/diagrams/
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

# my custom CSS for overriding Material theme styles
extra_css:
  - stylesheets/extra.css

#
#  Setup for My Social Media Icons Links (FontAwesome Icons)
#  - 우측 아래 각 Icon 클릭 시, 해당 링크로 이동
#  - Google Analytics, Disqus 등도 여기에 추가 가능
#
extra:
  #  - 우측 아래 각 Icon 클릭 시, 해당 링크로 이동
  # My Social Meida Icons Links (FontAwesome Icons)  
  social:
    
    - icon: fontawesome/solid/user
      link: https://jeonghunlee.github.io/
      name: User Profile

    - icon: fontawesome/brands/github
      link: https://github.com/JeonghunLee
      name: GitHub


copyright: >
  © 2026 Jeonghun Lee.
  All rights reserved.
