name: Deploy (mkdocs/doxygen) to GitHub Pages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r readthedoc_requirements.txt
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

         
      # 변경된 mkdocs.yml 사용
      - name: Build site (MkDocs)
        run: mkdocs build --config-file mkdocs.yml

      # 변경된 mkdocs.yml 사용        
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --config-file mkdocs.yml --force


      # 
      #  Automation for GitHub Release (Tag Push 시, 자동으로 Release 생성 및 Build 업로드)
      #     - https://github.com/JeonghunLee/wifisniffer/blob/main/.github/workflows/esp-idf.yml
      #    
      - name: Create GitHub Release and upload build
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: 
          body: |
            🚀 AI Agent with MCP Release
            ------------------------------------------
            * **Version**: ${{ github.ref_name }}            
            * **Release Date**: ${{ github.event.head_commit.timestamp }}      
            
            <br/>

            📄 **Documentation: (Supported Mkdocs)**
              -  [GitHub Pages: Mkdocs ](https://jeonghunlee.github.io/local-ai-agent-mcp/)
           
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
